function New-MutatorScript {
  param(
    [string]$Name,
    [ValidateSet('deathmatch','ctf','bomber-ball')][string]$Mode,
    [int]$Gravity = 100,
    [string]$Loadout = 'shotgun'
  )
@"
// Generated by Red Eclipse Ultimate Developer Toolkit
alias mutator_name "$Name"
sv_gamemode "$Mode"
sv_gravity $Gravity
sv_spawnweap "$Loadout"
"@
}

Export-ModuleMember -Function New-MutatorScript
